apiVersion: hops.ops.com.ai/v1alpha1
kind: GatewayAPIStack
metadata:
  name: gateway-api
  namespace: default
spec:
  clusterName: prod-cluster
  labels:
    team: platform
  namespace: gateway-api
  releaseName: gateway-api-crds
  # renovate: datasource=helm depName=gateway-api-crds registryUrl=https://wiremind.github.io/wiremind-helm-charts
  chartVersion: "1.5.1"
